[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
serde = { version = "1.0.213", features = ["derive"] }
slotmap = { version = "1.0.7", features = ["serde"] }
anyhow = "1.0.95"
log = "0.4.25"
hashbrown = "0.15.2"
