[package]
name = "zurie_ecs"
version = "0.0.0"
edition = "2024"

[dependencies]
zurie_shared = { path = "../zurie_shared" }
zurie_types = { path = "../zurie_types" }
serde = { workspace = true }
log = { workspace = true }
egui = { version = "0.29.1" }
hashbrown = { workspace = true }
