[package]
name = "zurie_ecs"
version = "0.0.0"
edition = "2021"

[dependencies]
zurie_shared = { path = "../zurie_shared" }
zurie_types = { path = "../zurie_types" }
serde = { workspace = true }
log = "0.4.22"
egui = { version = "0.29.1" }
