[package]
name = "vampire_like_demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zurie_mod_api = { path = "../zurie_mod_api" }
serde = {workspace = true}

[build]
target = "wasm32-unknown-unknown"
