[package]
name = "zurie_types"
version = "0.0.0"
edition = "2021"

[dependencies]
glam = { version = "0.29", features = ["mint"] }
num_enum = "*"
serde = { version = "1.0.213", features = ["derive"] }
flexbuffers = "2.0.0"
