[package]
name = "zurie_types"
version = "0.0.0"
edition = "2021"

[dependencies]
glam = { version = "0.29", features = ["mint"] }
num_enum = "0.7.3"
minicbor = { version = "*", features = ["derive", "std", "alloc"] }
