package zurie:engine@0.1.0;

interface core {
    record vec2 {
        x: f32,
        y: f32
    }

    record color {
        r: f32,
        g: f32,
        b: f32,
        a: f32
    }

    type entity-id = u64;
    type component-id = u64;
    type event-handle = u64;
    type sprite-handle = u64;
    type sound-handle = u64;
    type window-handle = u64;

    info: func(module-path: string, text: string);
    warn: func(module-path: string, text: string);
    error: func(module-path: string, text: string);
    debug: func(module-path: string, text: string);
    trace: func(module-path: string, text: string);
}

interface audio {
    use core.{sound-handle};

    load-sound: func(path: string) -> sound-handle;
    play-sound: func(handle: sound-handle);
}

interface input {
    use core.{vec2};

    //Keyboard
    key-clicked: func(key: u32) -> bool;
    subscribe-to-key-event: func(key: u32);

    //Mouse
    mouse-pos: func() -> vec2;
}

interface camera {
    use core.{vec2};

    record camera {
        position: vec2,
        zoom-factor: f32
    }

    get-camera: func() -> camera;
    set-camera: func(camera: camera);
    set-zoom: func(factor: f32);
    get-zoom: func() -> f32;
    set-position: func(position: vec2);
    get-position: func() -> vec2;
}

interface ecs {
    use core.{entity-id, component-id, vec2, color};


    variant component-data {
        none,
        str(string),
        vec2(vec2),
        color(color),
        raw(list<u8>),
        i32(s32),
        i64(s64),
        sprite(u64)
    }

    spawn-entity: func() -> entity-id;
    despawn-entity: func(entity: entity-id);
    register-component: func(name: string) -> component-id;
    set-component: func(entity: entity-id, component: component-id, data: component-data);
    get-component: func(entity: entity-id, component: component-id) -> option<component-data>;

    get-entities-with-component: func(component: component-id) -> list<entity-id>;
    get-entities-with-components: func(required: list<component-id>, optional: list<component-id>) -> list<entity-id>;
}

interface events {
    use core.{event-handle, entity-id, component-id, vec2, color};

    subscribe-by-name: func(name: string) -> event-handle;
    subscribe-by-handle: func(handle: event-handle);
    emit: func(handle: event-handle, data: event-data);

    variant event-data {
        none,
        str(string),
        vec2(vec2),
        color(color),
        raw(list<u8>),
        i32(s32),
        i64(s64)
    }
}

interface gui {
    use core.{window-handle};

    variant widget {
        label(string),
        button(string),
        input(string),
        checkbox(tuple<bool, string>)
    }

    variant widget-response {
        input(string),
        checked(bool),
        clicked(bool)
    }

    //window handle only valid for one frame
    create-window: func(title: string, widgets: list<widget>) -> list<widget-response>;
}

world zurie-mod {
    import core;
    import audio;
    import camera;
    import ecs;
    import events;
    import input;
    import gui;

    use core.{event-handle};
    use events.{event-data};

    export init: func();
    export update: func();
    export key-event: func(key-code: u32);
    export scroll: func(amount: f32);
    export event: func(handle: event-handle, data: event-data);
}
