[package]
name = "zurie_bin"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "zurie_engine"
path = "src/main.rs"

[dependencies]
zurie_core = { path = "../zurie_core" }
winit = { version = "0.30.5", features = ["rwh_05", "rwh_06"] }
env_logger = "0.11.5"
log = "0.4.22"
