[package]
name = "zurie_audio"
version = "0.0.0"
edition = "2021"

[dependencies]
kira = "0.10.0"
slotmap = {workspace = true}
log = {workspace = true}
anyhow = {workspace = true}
zurie_types = {path = "../zurie_types"}
[[bin]]
name = "zurie_audio_test"
path = "src/main.rs"
